spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_bound_community
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: localhost
#    port: 2525
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mail:
    host: smtp.gmail.com
    port: 465
    username: bookboundcommunity@gmail.com
    password: atxy kbbk qhco mczy
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          debug:
            true
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088
